set nocompatible
filetype on
filetype off
filetype plugin on
filetype plugin indent on
syntax on

"Vundle
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Bundle 'gmarik/vundle'

"My bundles
Bundle 'mattn/gist-vim'
Bundle 'Shougo/neocomplcache'
Bundle 'scrooloose/nerdtree'
Bundle 'scrooloose/nerdcommenter'
Bundle 'vim-scripts/OmniCppComplete'
Bundle 'ervandew/supertab'
Bundle 'kchmck/vim-coffee-script'
Bundle 'altercation/vim-colors-solarized'
Bundle 'jnwhiteh/vim-golang'
Bundle 'digitaltoad/vim-jade'
Bundle 'jelera/vim-javascript-syntax'

"Key bindings
:inoremap jj <Esc>

"Setup
set enc=utf-8 "encoding
set guioptions-=T "no toolbar macvim
set guifont=Andale\ Mono:h14 "font
set number "line numbers

"Indentation
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab

"Colorscheme
set background=dark
let g:solarized_termtrans=1
let g:solarized_contrast="high"
let g:solarized_visibility="high"
let g:solarized_termcolors=256
colorscheme solarized

"Autostart neocomplcache
let g:neocomplcache_enable_at_startup = 1

"NERDTree
map <C-e> :NERDTreeToggle<CR>:NERDTreeMirror<CR>
map <leader>e :NERDTreeFind<CR>
nmap <leader>nt :NERDTreeFind<CR>
let NERDTreeIgnore=['\.pyc', '\~$', '\.swo$', '\.swp$', '\.git', '\.hg', '\.svn', '\.bzr']
let NERDTreeChDirMode=0
let NERDTreeMouseMode=2
let NERDTreeShowBookmarks=1
let NERDTreeShowHidden=1

"Closetags.vim
"autocmd FileType html,xhtml,xml,htmldjango,htmljinja,eruby,mako source ~/.vim/bundle/closetag.vim
"autocmd FileType html,xhtml,xml,htmldjango,htmljinja,eruby,mako setlocal expandtab shiftwidth=2 tabstop=2 softtabstop=2

"Setup Supertab
let g:SuperTabDefaultCompletionType = "<C-X><C-O>"

"OmniCppComplete initialization
call omni#cpp#complete#Init()

"Vim-golang
set rtp+=$GOROOT/misc/vim
