set nocompatible
filetype on
filetype off
filetype plugin on
syntax on

"Vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

"My bundles
Plugin 'Shougo/neocomplcache'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/nerdcommenter'
Plugin 'altercation/vim-colors-solarized'
Plugin 'ervandew/supertab'

call vundle#end()
filetype plugin indent on

"Key bindings
:inoremap jj <Esc>

"Setup
set enc=utf-8 "encoding
set guioptions-=T "no toolbar macvim
set guifont=Andale\ Mono:h14 "font
set number "line numbers

"Search
set hlsearch
set incsearch

"Indentation
set smartindent
set tabstop=2
set shiftwidth=2
set expandtab

"Colorscheme
set background=dark
let g:solarized_termtrans=1
let g:solarized_contrast="high"
let g:solarized_visibility="high"
let g:solarized_termcolors=256
colorscheme solarized

"Autostart neocomplcache
let g:neocomplcache_enable_at_startup = 1

"NERDTree
map <C-e> :NERDTreeToggle<CR>:NERDTreeMirror<CR>
map <leader>e :NERDTreeFind<CR>
nmap <leader>nt :NERDTreeFind<CR>
let NERDTreeIgnore=['\.pyc', '\~$', '\.swo$', '\.swp$', '\.git', '\.hg', '\.svn', '\.bzr']
let NERDTreeChDirMode=0
let NERDTreeMouseMode=2
let NERDTreeShowBookmarks=1
let NERDTreeShowHidden=1

"Supertab
let g:SuperTabDefaultCompletionType = "<C-X><C-O>"

