# Check for Tools folder. If not use alternate directory
TOOLS=$HOME/Dropbox/Lance/Tools
if [[ ! -d "${TOOLS}" ]]; then TOOLS="/Volumes/Macintosh HD 2/Dropbox/Lance/Tools"; fi

# Path to oh-my-zsh configuration.
ZSH=$TOOLS/dotfiles/zsh/oh-my-zsh

# Set name of the theme to load.
export ZSH_THEME="mortalscumbagmod"

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Load plugins
plugins=(brew docker gem git node npm osx ruby rvm vagrant wd)

# Run oh-my-zsh
source $ZSH/oh-my-zsh.sh

# PATH
export PATH="/usr/local/bin:/usr/local/sbin:~/bin:$PATH"

# Java
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home

# Android
export PATH="$HOME/Library/Android/sdk/tools:$PATH"
export PATH="$HOME/Library/Android/sdk/platform-tools:$PATH"
export PATH="$HOME/Library/Android/sdk/ndk-bundle:$PATH"

# Haskell
export PATH="$HOME/Library/Haskell/bin:$PATH"

# Go-lang
GOPATH=$HOME/Projects/go
if ! ls $GOPATH 2>/dev/null 1>/dev/null; then GOPATH=$HOME/go; fi

# NVM
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh

# RVM
export PATH="$PATH:$HOME/.rvm/bin"
#[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# Homebrew Cask
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# alias commands
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias c='clear'
alias la='ls -a'
alias ll='ls -al'
alias ga.='git add . -A'
alias gru='git remote update --prune'
alias gig='git update-index --assume-unchanged'
alias glog="git log --color --graph\
    --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%C(bold blue)<%an>%Creset'\
    --abbrev-commit"
alias gtags="git tag -l -n1"
alias ghpages="git subtree push --prefix dist origin gh-pages"
alias npmls="npm ls --depth=0"
alias pgstart='postgres -D /usr/local/var/postgres'
alias sshconfig='vi ~/.ssh/config'
alias untar='for a in `ls -1 *.tar.gz`; do tar -zxvf $a; done'
alias updates='\
    brew update &&\
    brew upgrade --all &&\
    brew cleanup &&\
    brew cask cleanup &&\
    brew prune &&\
    rvm get stable &&\
    gem update --no-rdoc --no-ri &&\
    gem cleanup &&\
    npm cache clean &&\
    npm update -g'

# functions
vimrc() { command vi $TOOLS/dotfiles/vim/vimrc }
zshrc() { command vi $TOOLS/dotfiles/zsh/zshrc }

# ZSH Setup
#
# Autocomplete
autoload -Uz compinit && compinit

# Vim mode zsh
bindkey -v
bindkey -M viins 'jj' vi-cmd-mode

function zle-line-init zle-keymap-select {
    RPS1="${${KEYMAP/vicmd/-- NORMAL --}/(main|viins)/-- INSERT --}"
    RPS2=$RPS1
    zle reset-prompt
}
zle -N zle-line-init
zle -N zle-keymap-select

