# Check for dotfiles folder. If not use alternate directory
DOTFILES=$HOME/Dropbox/Lance/Tools/dotfiles
if [[ ! -d "${DOTFILES}" ]]; then DOTFILES="$HOME/.dotfiles"; fi

# Path to oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Path to zsh customizations
export ZSH_CUSTOM=$DOTFILES/zsh/custom

# Set name of the theme to load.
export ZSH_THEME="mortalscumbagmod"

# Load plugins
plugins=(brew colored-man-pages docker extract gem git node npm nvm osx pod ruby rvm tmux wd web-search)

# Run oh-my-zsh
source $ZSH/oh-my-zsh.sh

# PATH
export PATH="/usr/local/bin:/usr/local/sbin:~/bin:$PATH"

# Python3
export PATH="/Users/Lance/Library/Python/3.5/bin:$PATH"

# Java
export JAVA8_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home

# Android
export PATH="$HOME/Library/Android/sdk/tools:$PATH"
export PATH="$HOME/Library/Android/sdk/platform-tools:$PATH"
export PATH="$HOME/Library/Android/sdk/ndk-bundle:$PATH"

# Haskell
export PATH="$HOME/Library/Haskell/bin:$PATH"

# Go-lang
GOPATH=$HOME/Projects/go
if ! ls $GOPATH 2>/dev/null 1>/dev/null; then GOPATH=$HOME/go; fi

# NVM
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh

# Rbenv
eval "$(rbenv init -)"

# fastlane
export PATH="$HOME/.fastlane/bin:$PATH"
export FASTLANE_OPT_OUT_USAGE=1
. ~/.fastlane/completions/completion.sh

# Homebrew
export HOMEBREW_NO_ANALYTICS=1

#AWS CLI completion
source /usr/local/share/zsh/site-functions/_aws

# alias commands
# files
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias c='clear'
alias la='ls -a'
alias ll='ls -al'
# docker
alias dockercleanall='dockercleanc || true && dockercleani'
alias dockercleanc='printf "\n>>> Deleting stopped containers\n\n" && docker rm $(docker ps -a -q)'
alias dockercleani='printf "\n>>> Deleting untagged images\n\n" && docker rmi $(docker images -q -f dangling=true)'
alias dockerkillall='printf "\n>>> Stopping all containers\n\n" && docker kill $(docker ps -q)'
# git
alias ga.='git add . -A'
alias gig='git update-index --assume-unchanged'
alias glog="git log --color --graph\
    --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%C(bold blue)<%an>%Creset'\
    --abbrev-commit"
alias gru='git remote update --prune'
alias gtags="git tag -l -n1"
# other
alias ghpages="git subtree push --prefix dist origin gh-pages"
alias npmls="npm ls --depth=0"
alias pgstart='postgres -D /usr/local/var/postgres'
alias serve='http-server -p 9000 --cors'
alias sshconfig='vi ~/.ssh/config'
alias updates='\
    brew update &&\
    brew upgrade &&\
    brew cleanup &&\
    brew cask cleanup &&\
    brew prune &&\
    gem update --no-rdoc --no-ri &&\
    gem cleanup &&\
    npm cache clean &&\
    npm update -g'

# functions
vimrc() { command vi $DOTFILES/vim/vimrc }
zshrc() { command vi $DOTFILES/zsh/zshrc }

# ZSH Setup
#
# Autocomplete
autoload -Uz compinit && compinit

# Vim mode zsh
bindkey -v
bindkey -M viins 'jj' vi-cmd-mode

function zle-line-init zle-keymap-select {
    RPS1="${${KEYMAP/vicmd/-- NORMAL --}/(main|viins)/-- INSERT --}"
    RPS2=$RPS1
    zle reset-prompt
}
zle -N zle-line-init
zle -N zle-keymap-select

