#Added aws and node.js npm paths
export PATH="~/.ec2/bin/:/usr/local/share/npm/bin:/usr/local/bin:/usr/local/sbin:~/bin:$PATH"

#Load RVM function
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" 

#AWS EC2 info
export EC2_HOME=~/.ec2
export EC2_PRIVATE_KEY=`ls $EC2_HOME/aws-pk.pem`
export EC2_CERT=`ls $EC2_HOME/aws-cert.pem`
export EC2_URL=https://ec2.us-west-2.amazonaws.com

#Load Java home
export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Home/

#GO
export PATH=$PATH:/usr/local/go/bin

#GO projects
export GOPATH=$HOME/Development/other/golang
export PATH=$PATH:$HOME/Development/other/golang/bin
